Repository Goorm-OGJG/PBL-Instagram-BE, pull requests merged in 2023-08, with the labels that each got.

#11 :bug: comment entity mappedBy 설정
  src/main/java/ogjg/instagram/comment/domain/Comment.java
Labels: bug

#13 :necktie: Entity attribute 조건 추가
  src/main/java/ogjg/instagram/comment/domain/Comment.java
  src/main/java/ogjg/instagram/comment/domain/InnerComment.java
  src/main/java/ogjg/instagram/feed/domain/Feed.java
  src/main/java/ogjg/instagram/feed/domain/FeedMedia.java
  src/main/java/ogjg/instagram/follow/domain/Follow.java
  src/main/java/ogjg/instagram/follow/domain/FollowPK.java
  src/main/java/ogjg/instagram/follow/repository/FollowRepository.java
  src/main/java/ogjg/instagram/hashtag/domain/Hashtag.java
  src/main/java/ogjg/instagram/like/domain/CommentLike.java
  src/main/java/ogjg/instagram/like/domain/CommentLikePK.java
  src/main/java/ogjg/instagram/like/domain/FeedLike.java
  src/main/java/ogjg/instagram/like/domain/FeedLikePK.java
  src/main/java/ogjg/instagram/like/domain/InnerCommentLike.java
  src/main/java/ogjg/instagram/like/domain/InnerCommentLikePK.java
  src/main/java/ogjg/instagram/like/domain/StoryLike.java
  src/main/java/ogjg/instagram/like/domain/StoryLikePK.java
  src/main/java/ogjg/instagram/story/domain/Story.java
  src/main/java/ogjg/instagram/story/domain/StoryMedia.java
  src/main/java/ogjg/instagram/user/domain/Collection.java
  src/main/java/ogjg/instagram/user/domain/CollectionFeedPK.java
  src/main/java/ogjg/instagram/user/domain/StoryUserReadPK.java
  src/main/java/ogjg/instagram/user/domain/User.java
Labels: enhancement

#15 :sparkles: follow 기능 추가
  src/main/java/ogjg/instagram/follow/controller/FollowController.java
  src/main/java/ogjg/instagram/follow/domain/Follow.java
  src/main/java/ogjg/instagram/follow/domain/FollowPK.java
  src/main/java/ogjg/instagram/follow/repository/FollowRepository.java
  src/main/java/ogjg/instagram/follow/response/FollowResponse.java
  src/main/java/ogjg/instagram/follow/response/FollowedResponse.java
  src/main/java/ogjg/instagram/follow/service/FollowService.java
Labels: enhancement

#19 :sparkles: Profile 기능 추가
  src/main/java/ogjg/instagram/feed/dto/CommentThumbnailResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/FeedDetailResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/FeedListResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/FeedMediaResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/FollowingIdResponseDto.java
  src/main/java/ogjg/instagram/feed/repository/FeedRepository.java
  src/main/java/ogjg/instagram/feed/service/FeedService.java
  src/main/java/ogjg/instagram/like/service/LikeService.java
  src/main/java/ogjg/instagram/profile/controller/ProfileController.java
  src/main/java/ogjg/instagram/profile/dto/ProfileFeedDto.java
  src/main/java/ogjg/instagram/profile/dto/request/ProfileImgEditRequestDto.java
  src/main/java/ogjg/instagram/profile/dto/response/ProfileEditResponseDto.java
  src/main/java/ogjg/instagram/profile/dto/response/ProfileFeedResponseDto.java
  src/main/java/ogjg/instagram/profile/dto/response/ProfileResponseDto.java
  src/main/java/ogjg/instagram/profile/repository/CollectionFeedRepository.java
  src/main/java/ogjg/instagram/profile/repository/ProfileRepository.java
  src/main/java/ogjg/instagram/profile/service/ProfileService.java
  src/main/java/ogjg/instagram/search/dto/SearchHashtagResponseDto.java
  src/main/java/ogjg/instagram/search/dto/SearchHashtagResponseDtos.java
  src/main/java/ogjg/instagram/search/dto/SearchNicknameResponseDto.java
  src/main/java/ogjg/instagram/search/dto/SearchNicknameResponseDtos.java
  src/main/java/ogjg/instagram/search/dto/SearchResponseDto.java
  src/main/java/ogjg/instagram/user/controller/UserController.java
  src/main/java/ogjg/instagram/user/domain/User.java
  src/main/java/ogjg/instagram/user/repository/UserRepository.java
  src/main/java/ogjg/instagram/user/repository/UsersRepository.java
  src/main/java/ogjg/instagram/user/service/UserService.java
  src/main/java/ogjg/instagram/user/service/UsersService.java
Labels: enhancement

#30 :sparkles: story 기능 추가
  src/main/java/ogjg/instagram/story/controller/StoryController.java
  src/main/java/ogjg/instagram/story/domain/Story.java
  src/main/java/ogjg/instagram/story/domain/StoryMedia.java
  src/main/java/ogjg/instagram/story/dto/request/StoryMediaListDto.java
  src/main/java/ogjg/instagram/story/dto/request/StoryMediaSaveDto.java
  src/main/java/ogjg/instagram/story/dto/request/StoryUserReadDto.java
  src/main/java/ogjg/instagram/story/dto/response/StoryListDto.java
  src/main/java/ogjg/instagram/story/dto/response/StoryMediaDto.java
  src/main/java/ogjg/instagram/story/dto/response/StoryResponse.java
  src/main/java/ogjg/instagram/story/repository/StoryMediaRepository.java
  src/main/java/ogjg/instagram/story/repository/StoryReadRepository.java
  src/main/java/ogjg/instagram/story/repository/StoryRepository.java
  src/main/java/ogjg/instagram/story/repository/StoryRepositoryCustom.java
  src/main/java/ogjg/instagram/story/repository/StoryRepositoryCustomImpl.java
  src/main/java/ogjg/instagram/story/service/StoryService.java
Labels: enhancement

#32 검색 기능 구현
  src/main/java/ogjg/instagram/hashtag/domain/Hashtag.java
  src/main/java/ogjg/instagram/hashtag/domain/HashtagFeed.java
  src/main/java/ogjg/instagram/hashtag/domain/HashtagPK.java
  src/main/java/ogjg/instagram/hashtag/repository/HashtagFeedRepository.java
  src/main/java/ogjg/instagram/hashtag/repository/HashtagRepository.java
  src/main/java/ogjg/instagram/hashtag/service/HashtagFeedService.java
  src/main/java/ogjg/instagram/hashtag/service/HashtagService.java
  src/main/java/ogjg/instagram/search/controller/SearchController.java
  src/main/java/ogjg/instagram/search/dto/SearchHashtagResponseDto.java
  src/main/java/ogjg/instagram/search/dto/SearchHashtagResponseDtos.java
  src/main/java/ogjg/instagram/search/dto/SearchNicknameResponseDto.java
  src/main/java/ogjg/instagram/search/dto/SearchNicknameResponseDtos.java
  src/main/java/ogjg/instagram/search/dto/SearchResponseDto.java
  src/main/java/ogjg/instagram/search/dto/response/SearchHashtagResponseDto.java
  src/main/java/ogjg/instagram/search/dto/response/SearchNicknameResponseDto.java
  src/main/java/ogjg/instagram/search/service/SearchService.java
Labels: enhancement

#33 :sparkles: 피드 기능 구현
  src/main/java/ogjg/instagram/feed/controller/CollectionController.java
  src/main/java/ogjg/instagram/feed/controller/FeedController.java
  src/main/java/ogjg/instagram/feed/domain/Collection.java
  src/main/java/ogjg/instagram/feed/domain/CollectionFeed.java
  src/main/java/ogjg/instagram/feed/domain/CollectionFeedPK.java
  src/main/java/ogjg/instagram/feed/domain/Feed.java
  src/main/java/ogjg/instagram/feed/domain/FeedMedia.java
  src/main/java/ogjg/instagram/feed/dto/CommentThumbnailResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/FeedDetailResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/FeedListResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/FeedMediaResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/FollowingIdResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/request/FeedCreateRequestDto.java
  src/main/java/ogjg/instagram/feed/dto/response/FeedDetailResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/response/FeedListResponseDto.java
  src/main/java/ogjg/instagram/feed/dto/response/FeedMediaResponseDto.java
  src/main/java/ogjg/instagram/feed/repository/CollectionFeedRepository.java
  src/main/java/ogjg/instagram/feed/repository/FeedRepository.java
  src/main/java/ogjg/instagram/feed/service/CollectionService.java
  src/main/java/ogjg/instagram/feed/service/FeedService.java
  src/main/java/ogjg/instagram/follow/repository/FollowRepository.java
  src/main/java/ogjg/instagram/follow/service/FollowService.java
  src/main/java/ogjg/instagram/like/repository/FeedLikeRepository.java
  src/main/java/ogjg/instagram/like/service/FeedLikeService.java
  src/main/java/ogjg/instagram/user/domain/CollectionFeedPK.java
Labels: enhancement

#36 :sparkles: story 좋아요 상태 기능 추가
  src/main/java/ogjg/instagram/like/repository/StoryLikeRepository.java
  src/main/java/ogjg/instagram/like/service/StoryLikeService.java
Labels: enhancement

#49 :hammer: JWT 재발급 Bugfix
  src/main/java/ogjg/instagram/config/security/jwt/JwtUtils.java
  src/main/java/ogjg/instagram/config/security/login/LoginAuthSuccessHandler.java
  src/main/java/ogjg/instagram/user/domain/UserAuthentication.java
  src/main/java/ogjg/instagram/user/service/UserService.java
Labels: bug

#51 :hammer: 회원가입 요청 필드네임 변경
  src/main/java/ogjg/instagram/user/dto/SignupRequestDto.java
  src/main/java/ogjg/instagram/user/service/UserService.java
Labels: enhancement

#55 :sparkles: following, follower 프로필 추가
  src/main/java/ogjg/instagram/follow/controller/FollowController.java
  src/main/java/ogjg/instagram/follow/repository/FollowRepository.java
  src/main/java/ogjg/instagram/follow/response/FollowResponse.java
  src/main/java/ogjg/instagram/follow/response/FollowedResponse.java
  src/main/java/ogjg/instagram/follow/service/FollowService.java
Labels: enhancement

#46 :construction_worker: Github Actions CI script 작성
  .github/workflows/gradle.yml
Labels: enhancement

#57 :sparkles: userId 상수값 -> 토큰Id로 변경,like 가독성개선
  src/main/java/ogjg/instagram/like/controller/CommentLikeController.java
  src/main/java/ogjg/instagram/like/controller/FeedLikeController.java
  src/main/java/ogjg/instagram/like/controller/InnerCommentLikeController.java
  src/main/java/ogjg/instagram/like/controller/StoryLikeController.java
  src/main/java/ogjg/instagram/like/service/CommentLikeService.java
  src/main/java/ogjg/instagram/like/service/FeedLikeService.java
  src/main/java/ogjg/instagram/like/service/InnerCommentLikeService.java
  src/main/java/ogjg/instagram/like/service/StoryLikeService.java
Labels: enhancement

#62 :sparkles: 피드 보관함 삭제/대댓글 작성/프로필 보기 기능에 대한 예외처리 추가
  src/main/java/ogjg/instagram/comment/service/CommentService.java
  src/main/java/ogjg/instagram/feed/controller/CollectionController.java
  src/main/java/ogjg/instagram/feed/repository/CollectionFeedRepository.java
  src/main/java/ogjg/instagram/feed/service/CollectionService.java
  src/main/java/ogjg/instagram/feed/service/FeedService.java
Labels: enhancement

#64 :hammer: CICD 구현 테스트
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  start.sh
Labels: enhancement

#65 :bug: AWS_ROLE_ARN 변수 이름 수정
  .github/workflows/deploy.yml
Labels: enhancement

#71 jwt 쿠키 설정 및 임시 필터핸들러 생성
  src/main/java/ogjg/instagram/config/security/CustomGlobalFilterExceptionHandler.java
  src/main/java/ogjg/instagram/config/security/SecurityConfig.java
  src/main/java/ogjg/instagram/config/security/login/LoginAuthSuccessHandler.java
  src/main/java/ogjg/instagram/feed/service/CollectionFeedService.java
  src/main/java/ogjg/instagram/user/service/UserService.java
Labels: bug, enhancement

#75 Feed 작성/삭제 기능 오류 수정
  src/main/java/ogjg/instagram/comment/domain/Comment.java
  src/main/java/ogjg/instagram/comment/repository/CommentRepository.java
  src/main/java/ogjg/instagram/comment/service/CommentService.java
  src/main/java/ogjg/instagram/feed/controller/FeedController.java
  src/main/java/ogjg/instagram/feed/domain/Feed.java
  src/main/java/ogjg/instagram/feed/domain/FeedMedia.java
  src/main/java/ogjg/instagram/feed/dto/request/FeedCreateRequestDto.java
  src/main/java/ogjg/instagram/feed/dto/response/FeedListResponseDto.java
  src/main/java/ogjg/instagram/feed/repository/FeedMediaRepository.java
  src/main/java/ogjg/instagram/feed/service/FeedMediaService.java
  src/main/java/ogjg/instagram/feed/service/FeedService.java
  src/main/java/ogjg/instagram/user/domain/User.java
  src/test/java/ogjg/instagram/comment/CommentServiceTest.java
Labels: bug

#79 :bug: 누락된 Comment 응답 값 createAt 추가
  src/main/java/ogjg/instagram/comment/domain/Comment.java
Labels: bug

#81 :bug: follower/follwing 기능 대상 userId 사용하도록 수정
  src/main/java/ogjg/instagram/follow/controller/FollowController.java
Labels: bug

#77 저장/저장 취소 기능 오류 수정
  src/main/java/ogjg/instagram/feed/controller/CollectionController.java
  src/main/java/ogjg/instagram/feed/domain/Collection.java
  src/main/java/ogjg/instagram/feed/dto/request/FeedCreateRequestDto.java
  src/main/java/ogjg/instagram/feed/repository/CollectionFeedRepository.java
  src/main/java/ogjg/instagram/feed/repository/CollectionRepository.java
  src/main/java/ogjg/instagram/feed/service/CollectionFeedService.java
  src/main/java/ogjg/instagram/feed/service/CollectionService.java
  src/main/java/ogjg/instagram/feed/service/FeedService.java
  src/main/java/ogjg/instagram/profile/service/ProfileService.java
Labels: bug

#83 innerComment 불러오기 기능 누락된 기능 추가
  src/main/java/ogjg/instagram/comment/controller/CommentController.java
  src/main/java/ogjg/instagram/comment/controller/InnerCommentController.java
  src/main/java/ogjg/instagram/comment/dto/response/InnerCommentListResponseDto.java
  src/main/java/ogjg/instagram/comment/service/InnerCommentService.java
  src/main/java/ogjg/instagram/like/controller/InnerCommentLikeController.java
  src/main/java/ogjg/instagram/like/repository/InnerCommentLikeRepository.java
  src/main/java/ogjg/instagram/like/service/InnerCommentLikeService.java
Labels: bug

#85 story 시간 조건 및 정렬 추가
  src/main/java/ogjg/instagram/story/repository/StoryRepositoryCustomImpl.java
Labels: enhancement

#86 :rocket: Github Actions + Docker + AWS EB을 사용한 CICD 구현
  .github/workflows/cicd.yml
  .github/workflows/gradle.yml
  Dockerfile
  docker-compose.yml
  src/main/java/ogjg/instagram/config/HealthCheck.java
  start.sh
Labels: enhancement

#87 :rocket: plain.jar 생성하지 않도록 수정
  build.gradle
Labels: bug, enhancement

#92 :sparkles: 이메일, 닉네임 중복 검사 기능, 로그아웃 기능 구현
  src/main/java/ogjg/instagram/config/security/SecurityConfig.java
  src/main/java/ogjg/instagram/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/ogjg/instagram/user/controller/UserController.java
  src/main/java/ogjg/instagram/user/service/UserService.java
Labels: enhancement

#93 프로필 응답 식별자 수정, 팔로잉 목록 오류, 게시물 목록 서브쿼리 다중로우 오류 수정
  src/main/java/ogjg/instagram/follow/service/FollowService.java
  src/main/java/ogjg/instagram/profile/dto/response/ProfileFeedResponseDto.java
  src/main/java/ogjg/instagram/profile/dto/response/ProfileResponseDto.java
  src/main/java/ogjg/instagram/profile/repository/ProfileRepository.java
  src/main/java/ogjg/instagram/profile/service/ProfileService.java
Labels: bug

#96 :bug: charset 순서로 인한 인코딩 미적용 수정
  src/main/java/ogjg/instagram/config/security/CustomGlobalFilterExceptionHandler.java
Labels: bug

#95 :bug: 피드 댓글에 닉네임 표시가 잘못되는 오류 수정
  src/main/java/ogjg/instagram/feed/service/FeedService.java
Labels: bug

#99 유저 디폴트 이미지 추가
  src/main/java/ogjg/instagram/user/service/UserService.java
Labels: enhancement

#101 :hammer: 로그아웃 시 브라우저 내부에 존재하는 Refresh Token 삭제
  src/main/java/ogjg/instagram/user/controller/UserController.java
  src/main/java/ogjg/instagram/user/service/UserService.java
Labels: enhancement

#102 :hammer: Cookie 이름 수정 [hotfix]
  src/main/java/ogjg/instagram/user/service/UserService.java
Labels: bug

#105 :sparkles: 해시태그 검색 결과 페이지 기능 구현
  src/main/java/ogjg/instagram/hashtag/repository/HashtagRepository.java
  src/main/java/ogjg/instagram/search/controller/SearchController.java
  src/main/java/ogjg/instagram/search/dto/response/SearchHashtagResponseDto.java
  src/main/java/ogjg/instagram/search/dto/response/SearchHashtagResultResponseDto.java
  src/main/java/ogjg/instagram/search/repository/SearchRepository.java
  src/main/java/ogjg/instagram/search/service/SearchService.java
Labels: enhancement

#107 ✨ 비밀번호 찾기 기능 구현
  build.gradle
  src/main/java/ogjg/instagram/config/security/SecurityConfig.java
  src/main/java/ogjg/instagram/user/controller/UserController.java
  src/main/java/ogjg/instagram/user/domain/User.java
  src/main/java/ogjg/instagram/user/domain/UserAuthenticationNumber.java
  src/main/java/ogjg/instagram/user/dto/UserAuthRequestDto.java
  src/main/java/ogjg/instagram/user/repository/UserAuthenticationNumberRepository.java
  src/main/java/ogjg/instagram/user/service/UserService.java
Labels: enhancement

#112 :sparkles: innerComment 좋아요 목록 추가
  src/main/java/ogjg/instagram/like/controller/InnerCommentLikeController.java
  src/main/java/ogjg/instagram/like/dto/innerCommentLike/InnerCommentLikeUserResponse.java
  src/main/java/ogjg/instagram/like/repository/InnerCommentLikeRepository.java
  src/main/java/ogjg/instagram/like/service/InnerCommentLikeService.java
Labels: enhancement

#110 :bug: 유저를 팔로우하는지 여부를 판단하는 기능 변수 순서 수정, 변수 네이밍 수정
  src/main/java/ogjg/instagram/follow/repository/FollowRepository.java
  src/main/java/ogjg/instagram/follow/service/FollowService.java
  src/main/java/ogjg/instagram/like/service/CommentLikeService.java
  src/main/java/ogjg/instagram/like/service/FeedLikeService.java
  src/main/java/ogjg/instagram/profile/service/ProfileService.java
  src/main/java/ogjg/instagram/search/service/SearchService.java
Labels: bug

#114 :construction_worker: PR시 Build 되도록 워크플로우 작성
  .github/workflows/build.yml
Labels: enhancement

#113 :bug: followerMeToo 변수명 충돌 해결, isFollowingUser 메서드 따로 추가
  src/main/java/ogjg/instagram/follow/repository/FollowRepository.java
  src/main/java/ogjg/instagram/follow/service/FollowService.java
  src/main/java/ogjg/instagram/like/service/CommentLikeService.java
  src/main/java/ogjg/instagram/like/service/FeedLikeService.java
Labels: enhancement

#118 :bug: 잘못 구현한 follow 조회로직 삭제 후 기존 메서드 재활용
  src/main/java/ogjg/instagram/follow/repository/FollowRepository.java
  src/main/java/ogjg/instagram/follow/service/FollowService.java
  src/main/java/ogjg/instagram/profile/service/ProfileService.java
Labels: bug

#120 :bug:피드 목록에 팔로우한 사람 피드가 표시 안되는 오류 수정
  src/main/java/ogjg/instagram/feed/service/FeedService.java
  src/main/java/ogjg/instagram/follow/controller/FollowController.java
  src/main/java/ogjg/instagram/follow/service/FollowService.java
Labels: bug

#123 :sparkles: 태그 검색 결과 페이지 응답 좋아요, 댓글 개수 추가
  src/main/java/ogjg/instagram/search/dto/SearchHashTagCountDto.java
  src/main/java/ogjg/instagram/search/dto/response/SearchHashtagResultResponseDto.java
  src/main/java/ogjg/instagram/search/repository/SearchRepository.java
  src/main/java/ogjg/instagram/search/service/SearchService.java
Labels: enhancement
