Repository Goorm-OGJG/PBL-Instagram-BE, pull requests merged in 2023-09, with the labels that each got.

#125 :rocket: health check 경로에 대한 요청 권한 삭제
  src/main/java/ogjg/instagram/config/security/SecurityConfig.java
Labels: hotfix

#127 :sparkles: 팔로워목록 팔로워 삭제하기
  src/main/java/ogjg/instagram/follow/controller/FollowController.java
Labels: enhancement

#131 :bug: hashtag 검색 중복 태그 조회 재수정
  src/main/java/ogjg/instagram/hashtag/repository/HashtagFeedRepository.java
  src/main/java/ogjg/instagram/hashtag/repository/HashtagRepository.java
  src/main/java/ogjg/instagram/hashtag/service/HashtagFeedService.java
  src/main/java/ogjg/instagram/hashtag/service/HashtagService.java
  src/main/java/ogjg/instagram/search/dto/response/SearchHashtagResponseDto.java
  src/main/java/ogjg/instagram/search/service/SearchService.java
Labels: bug

#133 :bug: 리프레시 토큰 버그 수정
  src/main/java/ogjg/instagram/user/repository/UserAuthenticationRepository.java
  src/main/java/ogjg/instagram/user/service/UserService.java
Labels: bug
